-- Phase 0 RLS rollback baseline (auto-generated by phase0-rls-cutover.mjs)
-- captured 2026-05-19T21:51:35.229Z
-- Restores prior policies verbatim and the prior RLS-enabled flag.
-- Apply with: node scripts/phase0-rls-cutover.mjs rollback <this-file>
BEGIN;
-- departments
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname='public' AND tablename='departments' LOOP
    EXECUTE format('DROP POLICY IF EXISTS %I ON public.departments', p.policyname); END LOOP; END $$;
-- academic_years
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname='public' AND tablename='academic_years' LOOP
    EXECUTE format('DROP POLICY IF EXISTS %I ON public.academic_years', p.policyname); END LOOP; END $$;
-- rooms
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname='public' AND tablename='rooms' LOOP
    EXECUTE format('DROP POLICY IF EXISTS %I ON public.rooms', p.policyname); END LOOP; END $$;
-- courses
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname='public' AND tablename='courses' LOOP
    EXECUTE format('DROP POLICY IF EXISTS %I ON public.courses', p.policyname); END LOOP; END $$;
-- faculty
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname='public' AND tablename='faculty' LOOP
    EXECUTE format('DROP POLICY IF EXISTS %I ON public.faculty', p.policyname); END LOOP; END $$;
-- scheduled_courses
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname='public' AND tablename='scheduled_courses' LOOP
    EXECUTE format('DROP POLICY IF EXISTS %I ON public.scheduled_courses', p.policyname); END LOOP; END $$;
-- faculty_preferences
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname='public' AND tablename='faculty_preferences' LOOP
    EXECUTE format('DROP POLICY IF EXISTS %I ON public.faculty_preferences', p.policyname); END LOOP; END $$;
-- scheduling_constraints
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname='public' AND tablename='scheduling_constraints' LOOP
    EXECUTE format('DROP POLICY IF EXISTS %I ON public.scheduling_constraints', p.policyname); END LOOP; END $$;
-- release_time
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname='public' AND tablename='release_time' LOOP
    EXECUTE format('DROP POLICY IF EXISTS %I ON public.release_time', p.policyname); END LOOP; END $$;
-- pathways
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname='public' AND tablename='pathways' LOOP
    EXECUTE format('DROP POLICY IF EXISTS %I ON public.pathways', p.policyname); END LOOP; END $$;
-- pathway_courses
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname='public' AND tablename='pathway_courses' LOOP
    EXECUTE format('DROP POLICY IF EXISTS %I ON public.pathway_courses', p.policyname); END LOOP; END $$;
-- programs
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname='public' AND tablename='programs' LOOP
    EXECUTE format('DROP POLICY IF EXISTS %I ON public.programs', p.policyname); END LOOP; END $$;
-- user_programs
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname='public' AND tablename='user_programs' LOOP
    EXECUTE format('DROP POLICY IF EXISTS %I ON public.user_programs', p.policyname); END LOOP; END $$;
CREATE POLICY "Public read" ON public.academic_years AS PERMISSIVE FOR SELECT TO public USING (true);
CREATE POLICY "auth_insert_academic_years" ON public.academic_years AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK ((auth.uid() IS NOT NULL));
CREATE POLICY "auth_update_academic_years" ON public.academic_years AS PERMISSIVE FOR UPDATE TO authenticated USING ((auth.uid() IS NOT NULL)) WITH CHECK ((auth.uid() IS NOT NULL));
CREATE POLICY "Public read" ON public.courses AS PERMISSIVE FOR SELECT TO public USING (true);
CREATE POLICY "auth_insert_courses" ON public.courses AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK ((auth.uid() IS NOT NULL));
CREATE POLICY "auth_update_courses" ON public.courses AS PERMISSIVE FOR UPDATE TO authenticated USING ((auth.uid() IS NOT NULL)) WITH CHECK ((auth.uid() IS NOT NULL));
CREATE POLICY "Public read" ON public.departments AS PERMISSIVE FOR SELECT TO public USING (true);
CREATE POLICY "Public read" ON public.faculty AS PERMISSIVE FOR SELECT TO public USING (true);
CREATE POLICY "auth_insert_faculty" ON public.faculty AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK ((auth.uid() IS NOT NULL));
CREATE POLICY "auth_update_faculty" ON public.faculty AS PERMISSIVE FOR UPDATE TO authenticated USING ((auth.uid() IS NOT NULL)) WITH CHECK ((auth.uid() IS NOT NULL));
CREATE POLICY "Public read" ON public.faculty_preferences AS PERMISSIVE FOR SELECT TO public USING (true);
CREATE POLICY "auth_delete_faculty_preferences" ON public.faculty_preferences AS PERMISSIVE FOR DELETE TO authenticated USING ((auth.uid() IS NOT NULL));
CREATE POLICY "auth_insert_faculty_preferences" ON public.faculty_preferences AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK ((auth.uid() IS NOT NULL));
CREATE POLICY "auth_update_faculty_preferences" ON public.faculty_preferences AS PERMISSIVE FOR UPDATE TO authenticated USING ((auth.uid() IS NOT NULL)) WITH CHECK ((auth.uid() IS NOT NULL));
CREATE POLICY "Public read" ON public.release_time AS PERMISSIVE FOR SELECT TO public USING (true);
CREATE POLICY "auth_delete_release_time" ON public.release_time AS PERMISSIVE FOR DELETE TO authenticated USING ((auth.uid() IS NOT NULL));
CREATE POLICY "auth_insert_release_time" ON public.release_time AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK ((auth.uid() IS NOT NULL));
CREATE POLICY "auth_update_release_time" ON public.release_time AS PERMISSIVE FOR UPDATE TO authenticated USING ((auth.uid() IS NOT NULL)) WITH CHECK ((auth.uid() IS NOT NULL));
CREATE POLICY "Public read" ON public.rooms AS PERMISSIVE FOR SELECT TO public USING (true);
CREATE POLICY "auth_insert_rooms" ON public.rooms AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK ((auth.uid() IS NOT NULL));
CREATE POLICY "auth_update_rooms" ON public.rooms AS PERMISSIVE FOR UPDATE TO authenticated USING ((auth.uid() IS NOT NULL)) WITH CHECK ((auth.uid() IS NOT NULL));
CREATE POLICY "Public read" ON public.scheduled_courses AS PERMISSIVE FOR SELECT TO public USING (true);
CREATE POLICY "auth_delete_scheduled_courses" ON public.scheduled_courses AS PERMISSIVE FOR DELETE TO authenticated USING ((auth.uid() IS NOT NULL));
CREATE POLICY "auth_insert_scheduled_courses" ON public.scheduled_courses AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK ((auth.uid() IS NOT NULL));
CREATE POLICY "auth_update_scheduled_courses" ON public.scheduled_courses AS PERMISSIVE FOR UPDATE TO authenticated USING ((auth.uid() IS NOT NULL)) WITH CHECK ((auth.uid() IS NOT NULL));
CREATE POLICY "Public read" ON public.scheduling_constraints AS PERMISSIVE FOR SELECT TO public USING (true);
CREATE POLICY "auth_delete_scheduling_constraints" ON public.scheduling_constraints AS PERMISSIVE FOR DELETE TO authenticated USING ((auth.uid() IS NOT NULL));
CREATE POLICY "auth_insert_scheduling_constraints" ON public.scheduling_constraints AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK ((auth.uid() IS NOT NULL));
CREATE POLICY "auth_update_scheduling_constraints" ON public.scheduling_constraints AS PERMISSIVE FOR UPDATE TO authenticated USING ((auth.uid() IS NOT NULL)) WITH CHECK ((auth.uid() IS NOT NULL));
ALTER TABLE public.academic_years ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.courses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.departments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.faculty ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.faculty_preferences ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.release_time ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rooms ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.scheduled_courses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.scheduling_constraints ENABLE ROW LEVEL SECURITY;
COMMIT;
